# Generated by Django 5.0 on 2023-12-19 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=64)),
                ('separation', models.CharField(max_length=6)),
                ('names_count', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(default='', max_length=64)),
                ('groom_name', models.CharField(default='', max_length=64)),
                ('date', models.DateField(default=None)),
                ('venue', models.CharField(default='', max_length=64)),
                ('note', models.CharField(default='', max_length=512)),
                ('cover_image', models.ImageField(default='', upload_to='events/cover')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.eventtype')),
            ],
            options={
                'db_table': 'event_master',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'event_gallery',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_cover', models.ImageField(upload_to='events/gallery/collection')),
                ('uploaded_time', models.DateTimeField(blank=True, null=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.gallery')),
            ],
            options={
                'db_table': 'event_gallery_image',
            },
        ),
        migrations.CreateModel(
            name='CroppedGalleryFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/faces/')),
                ('face_locations', models.JSONField(blank=True, default=None, null=True)),
                ('face_embedding', models.JSONField(blank=True, default=None, null=True)),
                ('parent_face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.croppedgalleryface')),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.galleryimage')),
            ],
            options={
                'db_table': 'event_gallery_image_face',
            },
        ),
        migrations.CreateModel(
            name='UserSelfieRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=24)),
                ('email_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('selfie_image', models.ImageField(upload_to='user_selfies')),
                ('selfie_embedding', models.JSONField(blank=True, default=None, null=True)),
                ('last_matching', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'event_user_selfie_registration',
            },
        ),
    ]
