# Generated by Django 5.0 on 2023-12-19 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croppedgalleryface',
            old_name='album',
            new_name='gallery_image',
        ),
        migrations.AddField(
            model_name='croppedgalleryface',
            name='parent_face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.croppedgalleryface'),
        ),
        migrations.AddField(
            model_name='userselfieregistration',
            name='last_matching',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
