# Generated by Django 5.0 on 2023-12-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_album_croppedgalleryface_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='croppedgalleryface',
            table='event_gallery_image_face',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event_master',
        ),
        migrations.AlterModelTable(
            name='eventtypes',
            table='event_type',
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='event_gallery',
        ),
        migrations.AlterModelTable(
            name='galleryimage',
            table='event_gallery_image',
        ),
        migrations.AlterModelTable(
            name='userselfieregistration',
            table='event_user_selfie_registration',
        ),
    ]
