# Generated by Django 5.0 on 2023-12-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventTypes',
            new_name='EventType',
        ),
    ]
