# Generated by Django 5.0 on 2023-12-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facedetectionjobs',
            table='app_face_detection_schedules',
        ),
    ]
