# Generated by Django 5.0 on 2023-12-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_facedetectionjobs_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaceDetectionJobs',
            new_name='FaceDetectionJob',
        ),
    ]
