# Generated by Django 5.0 on 2023-12-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userdesignation_table_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdesignation',
            table='auth_user_designations',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_user_profile',
        ),
    ]
