# Generated by Django 5.0 on 2023-12-19 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappLogWelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=34)),
                ('send_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'whatsapp_log_welcome_message',
            },
        ),
        migrations.CreateModel(
            name='WhatsappLogSharedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=34)),
                ('send_time', models.DateTimeField()),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.galleryimage')),
            ],
            options={
                'db_table': 'whatsapp_log_photo_share',
            },
        ),
    ]
