# Generated by Django 5.0 on 2023-12-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='whatsapplogsharedphotos',
            table='whatsapp_log_photo_share',
        ),
        migrations.AlterModelTable(
            name='whatsapplogwelcomemessages',
            table='whatsapp_log_welcome_message',
        ),
    ]
