# Generated by Django 5.0 on 2023-12-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_eventtypes_eventtype'),
        ('whatsapp', '0002_alter_whatsapplogsharedphotos_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsappLogSharedPhotos',
            new_name='WhatsappLogSharedPhoto',
        ),
        migrations.RenameModel(
            old_name='WhatsappLogWelcomeMessages',
            new_name='WhatsappLogWelcomeMessage',
        ),
    ]
